matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk7
      android:
        components:
          - android-21
    - language: objective-c
      os: osx
      osx_image: xcode7.3